### ISSUE TITLE
Runtime Errors on both iOS and Android

### ISSUE THREAD

**Issue by LiamInJapan** [ConnectyCube/connectycube-reactnative-samples#295]
Hi Connectycube!

We're super grateful for your hard work on this. 
Unfortunately we've been having quite a hard time getting all parts of this working on both platforms via react native.
We have already had some exchange by email regarding this issue, and have taken the advice of:

1) Upgrading connectycube npm
2) Removing react-native-webrtc
3) Downloading the bitcode version of webrtc

We've had quite a few problems with step 3. Basically we inherited this code-base from another company and I have a feeling they were using some old/incompatible versions between react/connectycube/webrtc which is getting us into this funk, and as we're coming in half-way, it's proving quite difficult to solve.

We received the project at "react-native-connectycube": "^3.7.8"
and with guidance over the support email we changed this to "react-native-connectycube": "^3.10.0" and removed react-native-webrtc

A small problem with this is that the advice in 2 and 3 is a little contradictory! 
The reason for this is the [script to download the bitcode version of webrtc](https://github.com/ConnectyCube/react-native-webrtc/blob/master/tools/downloadBitcode.sh) first of all contains a link to a [non-existant file](https://dl.bintray.com/webrtc-builds/webrtc-builds/M87-1/WebRTC.tar.xz). Secondly, if we remove react-native-webrtc we also remove this script! 

However we managed to solve this by incorporating this script into our build process independent of react-native-webrtc as well as pointing it to a valid webrtc.tar.gz link (we are using [this page](https://github.com/react-native-webrtc/react-native-webrtc/releases) and this [tar](https://github.com/react-native-webrtc/react-native-webrtc/releases/download/1.92.2/WebRTC.tar.xz). We also tried this [tar](https://github.com/react-native-webrtc/react-native-webrtc/releases/download/1.89.0/WebRTC.tar.xz) with the same result)

Now it seems we can get the project to build and I _think_ its using this bitcode version, and we can also remove react-native-webrtc from the package.json

The problem now is that the call functionality still doesn't work on either iOS or Android at real-time.

On iOS, we get a react-native error before we even get to the users screen:

![IMG_6998](https://user-images.githubusercontent.com/1658103/163705116-b38a4ee8-6a43-428d-9fef-da9fe6ece8b2.jpg)

(I'm attaching the xcode logs too as that might give more insight. It seems that it is communicating with Connectycube because I can see the user list
[allLogs.log](https://github.com/ConnectyCube/connectycube-reactnative-samples/files/8501167/allLogs.log))

On Android we manage to get to the user-list screen, but then we get this warning and the call doesn't work:

![XRecorder_17042022_152641 1](https://user-images.githubusercontent.com/1658103/163705204-4f62e01c-b485-4a7b-a4af-e80f81a6d80e.jpg)

In any case, we're starting to get to the end of our ideas for what this might be. 
It would be massively appreciated if you could give us some advice on how to proceed with this!

**Comment by LiamInJapan** [comment]
The other thing we have tried is reverting back to a state earlier in the project that the calls _were_ working. Let me share this state with you:

"react-native-connectycube": "3.7.8",
"react-native-webrtc": "^1.84.1" < include this - it wasn't included in the above case

Set all bitcode settings to NO

When we roll right back to that point in the project, the calling works... But when we integrate these changes into our newest commit, it doesn't with the following errors on the caller and receiver:

![IMG_0115](https://user-images.githubusercontent.com/1658103/163995086-1753ea62-6f5e-4cf1-b570-144d7f168181.PNG)
![IMG_7008](https://user-images.githubusercontent.com/1658103/163995098-baac3417-805d-4cf3-b9a5-7e4c7bd34b4a.PNG)

(We can open the call screen, we just can't make the calls. The error happens on the outgoing call device at the point of making the call, the warning appears on the receiver at the point that the caller cancels the (unsuccessful) call

**Comment by LiamInJapan** [comment]
Note actually in relation to that last comment if I do a complete reclean, npm install and pod install it works.

However the calls only work when the video screen is open. If it's not, I can hear the call come through, but I can't see the incoming call popup. I also get this warning on the receivers side:

![IMG_0116](https://user-images.githubusercontent.com/1658103/164030849-39f538e0-f1d6-4647-8ec3-2f1c34c38175.PNG)

Any insight would be greatly appreciated!

**Comment by DaveLomber** [comment]
@LiamInJapan 

first of all, please ignore ConnectyCube fork of WebRTC lib

we always use the original one, e.g. this https://github.com/react-native-webrtc/react-native-webrtc/blob/master/tools/downloadBitcode.sh

Here is how the overall configuration looks like:

**package.json**

```
{
  "name": "com.myapp",
  "version": "1.0",
  "scripts": {
    "postinstall": "run-script-os && npx jetify",
    "postinstall:nix": "npx jetify",
    "postinstall:darwin": "cd ios && pod install &&  sh ../node_modules/react-native-webrtc/tools/downloadBitcode.sh",

    "dependencies": {
       "react-native-connectycube": "^3.17.0",  
        ...
    }
    
    ...
}
```


**ios/Podfile**

```
...

  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'
```


All the above configuration hints were taken from https://github.com/react-native-webrtc/react-native-webrtc/tree/master/Documentation

So it's more about proper configuration 

Anyway I see it's solved here https://github.com/ConnectyCube/connectycube-reactnative-samples/issues/295#issuecomment-1102743932

**Comment by LiamInJapan** [comment]
I'm afraid it's still broken. In fact, rolling back to a earlier commit where it _was_ working is now broken...

Our dev Reegesh is going to share his findings shortly.

**Comment by dizzy-why** [comment]
![package-jsonfile-1](https://user-images.githubusercontent.com/30871302/166863543-e9c21122-ca7f-4890-8ea3-c5d0074dac83.png)
![package-jsonfile-2](https://user-images.githubusercontent.com/30871302/166863547-f3517d77-c614-44ef-9d22-e132a7458a81.png)
![manifest1](https://user-images.githubusercontent.com/30871302/166863548-8d78b403-8f49-42d3-a5f2-4d4e86ccf122.png)
![manifest2](https://user-images.githubusercontent.com/30871302/166863550-46ac43a7-5876-4862-b17b-afc12bc564cb.png)
![settings-gradle-file](https://user-images.githubusercontent.com/30871302/166863551-783b32ce-8661-4512-8e5b-f2c4b797e155.png)
[

**Comment by dizzy-why** [comment]
The problem were are having currently is with Android build. IOS build works fine with above suggestion.
Currently what we get on console log on android build is 

>
TypeError: Cannot read property 'enumerateDevices' of null
TypeError: Cannot read property 'enumerateDevices' of null
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:123246:47)
    at tryCallTwo (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27700:9)
    at doResolve (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27864:25)
    at Promise (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27723:14)
    at enumerateDevices (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:123245:27)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:128261:42)
    at tryCallTwo (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27700:9)
    at doResolve (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27864:25)
    at Promise (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27723:14)
    at getMediaDevices (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:128257:27)
    at setMediaDevices (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:260584:74)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:260482:30)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:262512:42)
    at _performTransitionSideEffects (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:56202:22)
    at _receiveSignal (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:56144:45)
    at onResponderRelease (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:56053:34)
    at apply (native)
    at invokeGuardedCallbackImpl (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:9811:21)
    at apply (native)
    at invokeGuardedCallback (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:9905:42)
    at apply (native)
    at invokeGuardedCallbackAndCatchFirstError (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:9909:36)
    at executeDispatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:9981:48)
    at executeDispatchesInOrder (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:10001:26)
    at executeDispatchesAndRelease (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11076:35)
    at executeDispatchesAndReleaseTopLevel (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11085:43)
    at forEach (native)
    at forEachAccumulated (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:10143:22)
    at runEventsInBatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11100:27)
    at runExtractedPluginEventsInBatch (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11179:25)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11155:42)
    at batchedUpdates$1 (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:21804:20)
    at batchedUpdates (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11062:36)
    at _receiveRootNodeIDEvent (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11154:23)
    at receiveTouches (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:11207:34)
    at apply (native)
    at __callFunction (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3371:36)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3103:31)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3325:15)
    at callFunctionReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3102:21)
[Wed May 04 2022 12:18:34.775]  WARN     Possible Unhandled Promise Rejection (id: 1):
TypeError: Cannot read property 'getUserMedia' of null
TypeError: Cannot read property 'getUserMedia' of null
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:123445:34)
    at tryCallOne (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27691:16)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:27792:27)
    at apply (native)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:31343:26)
    at _callTimer (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:31231:17)
    at _callImmediatesPass (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:31270:17)
    at callImmediates (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:31487:33)
    at __callImmediates (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3342:35)
    at anonymous (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3128:34)
    at __guard (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3325:15)
    at flushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3127:21)
    at invokeCallbackAndReturnFlushedQueue (http://localhost:8081/index.bundle?platform=android&dev=true&minify=false:3120:33)

**Comment by DaveLomber** [comment]
ok this is very strange 

I suggest to do the following

1) can you go into `node_modules/react-native-connectycube/lib/cubeDependencies.js` and put the following logs:

```
try {
  ReactNativeWebRTC = require('react-native-webrtc')
  console.log("connect react-native-webrtc OK")
} catch(e) {
 console.log("connect react-native-webrtc Error", e)
  ReactNativeWebRTC = {};
}
```

Also

2) can you go into `node_modules/react-native-connectycube/lib/cubeInternalUtils.js` and put the following logs:

```
static isRNWebRTCAvailble() {
    console.log("IS_RN_ENV", IS_RN_ENV)
    
    if (IS_RN_ENV && typeof Expo === 'undefined') {
      const {
        RTCView,
        RTCPeerConnection,
        RTCIceCandidate,
        RTCSessionDescription,
        MediaStream, 
        mediaDevices
      } = require('./cubeDependencies')

    console.log("isRNWebRTCAvailble", RTCView && RTCPeerConnection && RTCIceCandidate && RTCSessionDescription && MediaStream && mediaDevices)

      return RTCView && RTCPeerConnection && RTCIceCandidate && RTCSessionDescription && MediaStream && mediaDevices
    }

    return false;
  }
```

so we could get more info what's going on there

Thank you

**Comment by LiamInJapan** [comment]
`[Mon May 09 2022 21:43:26.358]  LOG      IS_RN_ENV true
[Mon May 09 2022 21:43:26.364]  LOG      connect react-native-webrtc OK
[Mon May 09 2022 21:43:26.365]  LOG      isRNWebRTCAvailble {}
[Mon May 09 2022 21:43:26.366]  DEBUG    [bugsnag] Loaded!
[Mon May 09 2022 21:43:26.367]  LOG      Running "main" with {"rootTag":21}
[Mon May 09 2022 21:43:27.574]  LOG      IS_RN_ENV true
[Mon May 09 2022 21:43:27.613]  LOG      isRNWebRTCAvailble {}
[Mon May 09 2022 21:43:31.816]  LOG      [enable][stream]
`

**Comment by LiamInJapan** [comment]
@DaveLomber Is there any more on this issue please? It's really blocking us from finalising a project and getting it released

**Comment by LiamInJapan** [comment]
dialog.js
```
import React, { useEffect, useState } from "react";
import { ImageBackground, Text, TouchableOpacity, View } from "react-native";
import EStyleSheet from "react-native-extended-stylesheet";
import { shallowEqual, useSelector } from "react-redux";
import { getGroupMembers } from "../../../../api/GroupAPI";

const Dialog = ({ navigation, group, dialog, route }) => {
  const userId = useSelector((state) => state.profile.userId);
  const [opponentsIds, setOpponentsIds] = useState([]);

  useEffect(() => {
    fetch();
  }, []);

  const fetch = async () => {
    const members = (await getGroupMembers(group.id)).filter(
      (x) => x.chatId != null && x.userId != userId
    );
    setOpponentsIds(members.map((x) => x.chatId));
    console.log("Members: ", opponentsIds);
  };
  const users = useSelector(
    (state) => state.group.allGroupMembers,
    shallowEqual
  );
  return (
    <TouchableOpacity
      onPress={() => {
        if (opponentsIds.length > 0) {
          navigation.navigate("CallSelect", {
            userId,
            opponentsIds,
            users,
          });
        } else {
          alert(
            "You are in a group on your own. Either invite some friends and\n" +
              "                family with the “Invite” functionality, or get a friend to\n" +
              "                invite you to their group"
          );
        }
      }}
    >
      <View style={styles.dialog}>
        <ImageBackground
          source={require("../../../../../assets/albumBG25.png")}
          style={styles.background}
        >
          <View>
            <View style={styles.textTop}>
              <Text style={styles.nameText}>{group.ownerName}'s Group</Text>
            </View>
          </View>
        </ImageBackground>
      </View>
    </TouchableOpacity>
  );
};

const styles = EStyleSheet.create({
  dialog: {
    margin: "10 rem",
    padding: "1 rem",
    backgroundColor: "#FFF",
    width: "95%",
    flex: 1,
    alignSelf: "center",
    flexDirection: "row",
    borderRadius: "5 rem",
    borderColor: "#902180",
    borderBottomWidth: "2 rem",
  },
  background: {
    height: "100%",
    width: "100%",
  },
  nameText: {
    fontSize: "16 rem",
    fontWeight: "bold",
    color: "#000",
  },
  textTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    padding: "10rem",
  },
  textBottom: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingLeft: "10rem",
    paddingBottom: "5rem",
    paddingRight: "10rem",
  },
  isTypingText: {
    color: "green",
    fontStyle: "italic",
  },
  messageText: {
    width: "80%",
  },
  messageNumber: {
    color: "green",
  },
});

export default Dialog;

```

**Comment by LiamInJapan** [comment]
GroupList/index.js
```
import React, { useEffect, useState } from "react";
import { SafeAreaView, View, Dimensions, Text, FlatList } from "react-native";
import { LinearGradient } from "expo-linear-gradient";

import EStyleSheet from "react-native-extended-stylesheet";
import { useFocusEffect } from "@react-navigation/native";
import { landscape } from "../../../helpers/orientation";

import { MaterialCommunityIcons } from "@expo/vector-icons";
import { getGroups, setChatIdAsync } from "../../../api/GroupAPI";
import Loading from "../../../helpers/loading";
import { useSelector } from "react-redux";
import Dialog from "./elements/dialog";
import {
  createDialogAsync,
  fetchDialogsFromServer,
  isConnected,
} from "../../../services/chat";

const GroupList = ({ navigation, route }) => {
  const [groups, setGroups] = useState([]);
  const dialogs = useSelector((state) => state.chatDialog);

  const [isLoading, setIsLoading] = useState(true);
  const [screenLand, setScreenLand] = useState(landscape());
  const { width } = Dimensions.get("window");
  const userId = useSelector((state) => state.profile.userId);
  const setData = async () => {
    try {
      const [groupData, _] = await Promise.all([
        getGroups(),
        fetchDialogsFromServer(),
      ]);
      const myGroup = groupData.groups.find((x) => x.ownerId == userId);
      if (myGroup && myGroup.chatId === null) {
        const myGroupChat = await createDialogAsync(
          `${myGroup.ownerName}'s Group`
        );

        await setChatIdAsync(myGroup.id, myGroupChat.id);
        myGroup.chatId = myGroupChat.id;
      }

      setGroups(groupData.groups);
    } catch (error) {
      console.log("GetGroups error :", error);
    } finally {
      setIsLoading(false);
    }
  };
  useFocusEffect(
    React.useCallback(() => {
      setData();
    }, [])
  );

  useEffect(() => {
    console.log("Dialogs: ", dialogs);
    console.log("Groups: ", groups);
  });

  if (isLoading) return <Loading />;

  return (
    <SafeAreaView style={styles.container}>
      <View style={{ width, height: "100%" }}>
        <LinearGradient
          colors={["#220751", "#504ca3", "transparent"]}
          style={styles.linearGradient}
        >
          <View
            style={
              screenLand ? styles.headerContainerLS : styles.headerContainer
            }
          >
            <View style={styles.headerInner}>
              <MaterialCommunityIcons
                name="chat"
                style={styles.icon}
                color="#fff"
              />

              <Text style={styles.headerText}>Select Group</Text>
            </View>
          </View>

          <View style={styles.groupsContainer}>
            <FlatList
              keyExtractor={(item) => item.id.toString()}
              data={groups}
              renderItem={({ item }) => {
                const dialog = dialogs.find((x) => x.id == item.chatId);

                if (dialog)
                  return (
                    <Dialog
                      navigation={navigation}
                      group={item}
                      dialog={dialog}
                      route={route}
                    />
                    // <Text>{item.ownerName}'s Group</Text>
                  );

                return null;
              }}
            />
          </View>
        </LinearGradient>
      </View>
    </SafeAreaView>
  );
};

const styles = EStyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "white",
    alignItems: "center",
    justifyContent: "center",
  },
  linearGradient: {
    width: "100%",
    height: "100%",
    opacity: 0.95,
    justifyContent: "center",
    alignItems: "center",
  },
  headerContainer: {
    flex: 0.5,
    flexDirection: "row",
    backgroundColor: "#233366",
    width: "90%",
    marginTop: "10 rem",
    marginBottom: "10 rem",
    borderRadius: "20 rem",
  },
  headerContainerLS: {
    flex: 1,
    flexDirection: "row",
    backgroundColor: "#233366",
    width: "90%",
    marginTop: "10 rem",
    marginBottom: "10 rem",
    borderRadius: "20 rem",
  },
  headerText: {
    color: "#fff",
    fontSize: "25 rem",
    paddingLeft: "10 rem",
  },
  icon: {
    fontSize: "36 rem",
  },
  headerInner: {
    flexDirection: "row",
    paddingLeft: "20 rem",
    paddingTop: "5 rem",
    paddingBottom: "5 rem",
    alignItems: "center",
  },
  groupsContainer: {
    flex: 4,
    width: "90%",
    marginBottom: 25,
  },
  listItem: {
    margin: "10 rem",
    padding: "1 rem",
    backgroundColor: "#FFF",
    width: "95%",
    flex: 1,
    alignSelf: "center",
    flexDirection: "row",
    borderRadius: "5 rem",
    borderColor: "#902180",
    borderBottomWidth: "2 rem",
  },
  item: {
    height: "100%",
    width: "100%",
    flexDirection: "row",
    justifyContent: "center",
  },
  listItemTitleText: {
    fontSize: "16 rem",
    fontWeight: "bold",
    color: "#000",
    paddingTop: "10rem",
    paddingBottom: "10rem",
  },
});

export default GroupList;

```

**Comment by LiamInJapan** [comment]
VideoCall/index.js
```
import ConnectyCube from "react-native-connectycube";
import Sound from "react-native-sound";

import React, { useEffect, useState } from "react";
import { View, Text } from "react-native";
import { shallowEqual, useSelector } from "react-redux";
import { RTCView } from "react-native-connectycube";
import EStyleSheet from "react-native-extended-stylesheet";
// outgoingCall = require('../../../../assets')
const VideoCall = () => {
  const userId = useSelector((state) => state.profile.userId, shallowEqual);
  const opponentsIds = [];
  const [_session, set_session] = useState(null);
  const [stream, setStream] = useState(null);
  const callIds = [userId, ...opponentsIds];
  const outgoingCall = new Sound(
    require("../../../../assets/sounds/dialing.mp3")
  );
  const incomingCall = new Sound(
    require("../../../../assets/sounds/calling.mp3")
  );
  const endCall = new Sound(require("../../../../assets/sounds/end_call.mp3"));
  const [mediaDevices, setMediaDevices] = useState([]);
  const updateMediaDevices = () => {
    return ConnectyCube.videochat.getMediaDevices().then((mediaDevices) => {
      setMediaDevices(mediaDevices);
    });
  };

  useEffect(() => {
    // getUserPermission();
    startCall();
    setTimeout(() => {
      stopCall();
    }, 5000);
  }, []);

  const getUserPermission = () => {
    const mediaParams = {
      audio: true,
      video: true,
    };

    session
      .getUserMedia(mediaParams)
      .then((localStream) => {})
      .catch((error) => {});
  };
  const playSound = (type) => {
    switch (type) {
      case "outgoing":
        outgoingCall.setNumberOfLoops(-1);
        outgoingCall.play();
        break;
      case "incoming":
        incomingCall.setNumberOfLoops(-1);
        incomingCall.play();
        break;
      case "end":
        endCall.play();
        break;

      default:
        break;
    }
  };

  const startCall = () => {
    const sessionType = ConnectyCube.videochat.CallType.VIDEO;
    const additionalOptions = {};
    const session = ConnectyCube.videochat.createNewSession(
      callIds,
      sessionType,
      additionalOptions
    );
    set_session(session);
    const mediaParams = {
      audio: true,
      video: { facingMode: "user" },
    };
    session.getUserMedia(mediaParams).then((stream) => {
      set_session({ ..._session, call: {} });
      setStream(stream);
      return stream;
    });
  };

  const stopSounds = () => {
    if (incomingCall.isPlaying()) {
      incomingCall.pause();
    }
    if (outgoingCall.isPlaying()) {
      outgoingCall.pause();
    }
  };

  const stopCall = () => {
    stopSounds();

    if (_session) {
      playSound("end");
      set_session.stop({});
      ConnectyCube.videochat.clearSession(_session.ID);
      set_session(null);
      setMediaDevices([]);
    }
  };
  if (!stream)
    return (
      <View>
        <Text>"Loading..."</Text>
      </View>
    );
  return (
    <RTCView
      objectFit="cover"
      style={styles.blackView}
      key={userId}
      streamURL={stream.toURL()}
    />
  );
};

const styles = EStyleSheet.create({
  blackView: {
    flex: 1,
    backgroundColor: "black",
  },
  inColumn: {
    flex: 1,
    flexDirection: "column",
  },
  inRow: {
    flex: 1,
    flexDirection: "row",
  },
});

export default VideoCall;
```

**Comment by LiamInJapan** [comment]
VideoScreen/CallingLoader.js
```
import React from "react";
import { ActivityIndicator, View, Text, StyleSheet } from "react-native";

export default ({ name }) => (
  <View style={styles.container}>
    <View style={styles.info}>
      <Text style={styles.text}>{name}</Text>
      <ActivityIndicator size="small" color="white" />
    </View>
  </View>
);

const styles = StyleSheet.create({
  container: {
    ...StyleSheet.absoluteFill,
    flex: 1,
    justifyContent: "center",
  },
  info: {
    flexDirection: "row",
    justifyContent: "center",
  },
  text: {
    fontSize: 16,
    color: "white",
    marginRight: 16,
  },
});

```

**Comment by LiamInJapan** [comment]
VideoScreen/index.js
```
import React from "react";
import { SafeAreaView, StatusBar, View } from "react-native";
import ConnectyCube from "react-native-connectycube";
import AwesomeAlert from "react-native-awesome-alerts";
import RTCViewGrid from "./RTCViewGrid";
import { CallService } from "../../../services";
import ToolBar from "./ToolBar";
import UsersSelect from "./UsersSelect";
import Loading from "../../../helpers/loading";

class VideoScreen extends React.Component {
  constructor(props) {
    super(props);
    this._session = null;
    this.opponentsIds = props.route.params.opponentsIds;
    this.state = {
      localStream: null,
      remoteStreams: [],
      selectedUsersIds: [],
      isActiveSelect: true,
      isActiveCall: false,
      isIncomingCall: false,
    };
    this._setUpListeners();
  }

  componentDidMount() {}
  componentWillUnmount() {
    CallService.stopCall();
  }

  componentDidUpdate(prevProps, prevState) {
    const currState = this.state;

    if (
      prevState.remoteStreams.length === 1 &&
      currState.remoteStreams.length === 0
    ) {
      CallService.stopCall();
      this.resetState();
    }
  }

  showInomingCallModal = (session) => {
    this._session = session;
    this.setState({ isIncomingCall: true });
  };

  hideInomingCallModal = () => {
    this._session = null;
    this.setState({ isIncomingCall: false });
  };

  selectUser = (userId) => {
    this.setState((prevState) => ({
      selectedUsersIds: [...prevState.selectedUsersIds, userId],
    }));
  };

  unselectUser = (userId) => {
    this.setState((prevState) => ({
      selectedUsersIds: prevState.selectedUsersIds.filter(
        (id) => userId !== id
      ),
    }));
  };

  closeSelect = () => {
    this.setState({ isActiveSelect: false });
  };

  setOnCall = () => {
    this.setState({ isActiveCall: true });
  };

  initRemoteStreams = (opponentsIds) => {
    const emptyStreams = opponentsIds.map((userId) => ({
      userId,
      stream: null,
    }));

    this.setState({ remoteStreams: emptyStreams });
  };

  updateRemoteStream = (userId, stream) => {
    this.setState(({ remoteStreams }) => {
      const updatedRemoteStreams = remoteStreams.map((item) => {
        if (item.userId === userId) {
          return { userId, stream };
        }

        return { userId: item.userId, stream: item.stream };
      });

      return { remoteStreams: updatedRemoteStreams };
    });
  };

  removeRemoteStream = (userId) => {
    this.setState(({ remoteStreams }) => ({
      remoteStreams: remoteStreams.filter((item) => item.userId !== userId),
    }));
  };

  setLocalStream = (stream) => {
    this.setState({ localStream: stream });
  };

  resetState = () => {
    this.setState({
      localStream: null,
      remoteStreams: [],
      selectedUsersIds: [],
      isActiveSelect: true,
      isActiveCall: false,
    });
  };

  _setUpListeners() {
    ConnectyCube.videochat.onCallListener = this._onCallListener;
    ConnectyCube.videochat.onAcceptCallListener = this._onAcceptCallListener;
    ConnectyCube.videochat.onRejectCallListener = this._onRejectCallListener;
    ConnectyCube.videochat.onStopCallListener = this._onStopCallListener;
    ConnectyCube.videochat.onUserNotAnswerListener =
      this._onUserNotAnswerListener;
    ConnectyCube.videochat.onRemoteStreamListener =
      this._onRemoteStreamListener;
  }

  _onPressAccept = () => {
    CallService.acceptCall(this._session).then((stream) => {
      const { opponentsIDs, initiatorID, currentUserID } = this._session;
      const opponentsIds = [initiatorID, ...opponentsIDs].filter(
        (userId) => currentUserID !== userId
      );

      this.initRemoteStreams(opponentsIds);
      this.setLocalStream(stream);
      this.closeSelect();
      this.hideInomingCallModal();
    });
  };

  _onPressReject = () => {
    CallService.rejectCall(this._session);
    this.hideInomingCallModal();
  };

  _onCallListener = (session, extension) => {
    CallService.processOnCallListener(session)
      .then(() => this.showInomingCallModal(session))
      .catch(this.hideInomingCallModal);
  };

  _onAcceptCallListener = (session, userId, extension) => {
    CallService.processOnAcceptCallListener(session, userId, extension)
      .then(this.setOnCall)
      .catch(this.hideInomingCallModal);
  };

  _onRejectCallListener = (session, userId, extension) => {
    CallService.processOnRejectCallListener(session, userId, extension)
      .then(() => this.removeRemoteStream(userId))
      .catch(this.hideInomingCallModal);
  };

  _onStopCallListener = (session, userId, extension) => {
    const isStoppedByInitiator = session.initiatorID === userId;

    CallService.processOnStopCallListener(userId, isStoppedByInitiator)
      .then(() => {
        if (isStoppedByInitiator) {
          this.resetState();
        } else {
          this.removeRemoteStream(userId);
        }
      })
      .catch(this.hideInomingCallModal);
  };

  _onUserNotAnswerListener = (session, userId) => {
    CallService.processOnUserNotAnswerListener(userId)
      .then(() => this.removeRemoteStream(userId))
      .catch(this.hideInomingCallModal);
  };

  _onRemoteStreamListener = (session, userId, stream) => {
    CallService.processOnRemoteStreamListener(userId)
      .then(() => {
        this.updateRemoteStream(userId, stream);
        this.setOnCall();
      })
      .catch(this.hideInomingCallModal);
  };

  render() {
    const {
      localStream,
      remoteStreams,
      selectedUsersIds,
      isActiveSelect,
      isActiveCall,
      isIncomingCall,
    } = this.state;

    const initiatorName = isIncomingCall
      ? CallService.getUserById(
          this._session.initiatorID,
          "name",
          this.props.route.params.users
        )
      : "";
    const localStreamItem = localStream
      ? [{ userId: "localStream", stream: localStream }]
      : [];
    const streams = [...remoteStreams, ...localStreamItem];

    CallService.setSpeakerphoneOn(remoteStreams.length > 0);
    if (!this.opponentsIds) return <Loading />;
    return (
      <SafeAreaView style={{ flex: 1, backgroundColor: "white" }}>
        <StatusBar backgroundColor="black" barStyle="light-content" />
        <RTCViewGrid streams={streams} />
        <UsersSelect
          isActiveSelect={isActiveSelect}
          opponentsIds={this.opponentsIds}
          selectedUsersIds={selectedUsersIds}
          selectUser={this.selectUser}
          unselectUser={this.unselectUser}
        />
        <ToolBar
          selectedUsersIds={selectedUsersIds}
          localStream={localStream}
          isActiveSelect={isActiveSelect}
          isActiveCall={isActiveCall}
          closeSelect={this.closeSelect}
          initRemoteStreams={this.initRemoteStreams}
          setLocalStream={this.setLocalStream}
          resetState={this.resetState}
        />
        <AwesomeAlert
          show={isIncomingCall}
          showProgress={false}
          title={`Incoming call from ${initiatorName}`}
          closeOnTouchOutside={false}
          closeOnHardwareBackPress={true}
          showCancelButton={true}
          showConfirmButton={true}
          cancelText="Reject"
          confirmText="Accept"
          cancelButtonColor="red"
          confirmButtonColor="green"
          onCancelPressed={this._onPressReject}
          onConfirmPressed={this._onPressAccept}
          onDismiss={this.hideInomingCallModal}
          alertContainerStyle={{ zIndex: 1 }}
          titleStyle={{ fontSize: 21 }}
          cancelButtonTextStyle={{ fontSize: 18 }}
          confirmButtonTextStyle={{ fontSize: 18 }}
        />
      </SafeAreaView>
    );
  }
}

export default VideoScreen;

```

**Comment by LiamInJapan** [comment]
VideoScreen/RTCViewGrid.js
```
import React from "react";
import { View, StyleSheet } from "react-native";
import { RTCView } from "react-native-connectycube";
import { CallService } from "../../../services";
import { users } from "../../../services/call/config";
import CallingLoader from "./CallingLoader";

export default ({ streams }) => {
  const RTCViewRendered = ({ userId, stream }) => {
    if (stream) {
      return (
        <RTCView
          objectFit="cover"
          style={styles.blackView}
          key={userId}
          streamURL={stream.toURL()}
        />
      );
    }

    return (
      <View style={styles.blackView}>
        <CallingLoader name={CallService.getUserById(userId, "name")} />
      </View>
    );
  };

  const streamsCount = streams.length;
  let RTCListView = null;

  switch (streamsCount) {
    case 1:
      RTCListView = (
        <RTCViewRendered
          userId={streams[0].userId}
          stream={streams[0].stream}
        />
      );
      break;

    case 2:
      RTCListView = (
        <View style={styles.inColumn}>
          <RTCViewRendered
            userId={streams[0].userId}
            stream={streams[0].stream}
          />
          <RTCViewRendered
            userId={streams[1].userId}
            stream={streams[1].stream}
          />
        </View>
      );
      break;

    case 3:
      RTCListView = (
        <View style={styles.inColumn}>
          <View style={styles.inRow}>
            <RTCViewRendered
              userId={streams[0].userId}
              stream={streams[0].stream}
            />
            <RTCViewRendered
              userId={streams[1].userId}
              stream={streams[1].stream}
            />
          </View>
          <RTCViewRendered
            userId={streams[2].userId}
            stream={streams[2].stream}
          />
        </View>
      );
      break;

    case 4:
      RTCListView = (
        <View style={styles.inColumn}>
          <View style={styles.inRow}>
            <RTCViewRendered
              userId={streams[0].userId}
              stream={streams[0].stream}
            />
            <RTCViewRendered
              userId={streams[1].userId}
              stream={streams[1].stream}
            />
          </View>
          <View style={styles.inRow}>
            <RTCViewRendered
              userId={streams[2].userId}
              stream={streams[2].stream}
            />
            <RTCViewRendered
              userId={streams[3].userId}
              stream={streams[3].stream}
            />
          </View>
        </View>
      );
      break;

    default:
      break;
  }

  return <View style={styles.blackView}>{RTCListView}</View>;
};

const styles = StyleSheet.create({
  blackView: {
    flex: 1,
    backgroundColor: "black",
  },
  inColumn: {
    flex: 1,
    flexDirection: "column",
  },
  inRow: {
    flex: 1,
    flexDirection: "row",
  },
});

```

**Comment by LiamInJapan** [comment]
VideoScreen/ToolBar.js
```
import React, { Component } from "react";
import { StyleSheet, SafeAreaView, TouchableOpacity, View } from "react-native";
import { CallService } from "../../../services";
import MaterialIcon from "react-native-vector-icons/MaterialIcons";

export default class ToolBar extends Component {
  state = {
    isAudioMuted: false,
    isFrontCamera: true,
  };

  static getDerivedStateFromProps(props, state) {
    let derivedState = {};

    if (!props.isActiveCall) {
      derivedState.isAudioMuted = false;
      derivedState.isFrontCamera = true;
    }

    return derivedState;
  }

  startCall = () => {
    const { selectedUsersIds, closeSelect, initRemoteStreams, setLocalStream } =
      this.props;

    if (selectedUsersIds.length === 0) {
      CallService.showToast("Select at less one user to start Videocall");
    } else {
      closeSelect();
      initRemoteStreams(selectedUsersIds);
      CallService.startCall(selectedUsersIds).then(setLocalStream);
    }
  };

  stopCall = () => {
    const { resetState } = this.props;

    CallService.stopCall();
    resetState();
  };

  switchCamera = () => {
    const { localStream } = this.props;

    CallService.switchCamera(localStream);
    this.setState((prevState) => ({ isFrontCamera: !prevState.isFrontCamera }));
  };

  muteUnmuteAudio = () => {
    this.setState((prevState) => {
      const mute = !prevState.isAudioMuted;
      CallService.setAudioMuteState(mute);
      return { isAudioMuted: mute };
    });
  };

  _renderCallStartStopButton = (isCallInProgress) => {
    const style = isCallInProgress ? styles.buttonCallEnd : styles.buttonCall;
    const onPress = isCallInProgress ? this.stopCall : this.startCall;
    const type = isCallInProgress ? "call-end" : "call";

    return (
      <TouchableOpacity
        style={[styles.buttonContainer, style]}
        onPress={onPress}
      >
        <MaterialIcon name={type} size={32} color="white" />
      </TouchableOpacity>
    );
  };

  _renderMuteButton = () => {
    const { isAudioMuted } = this.state;
    const type = isAudioMuted ? "mic-off" : "mic";

    return (
      <TouchableOpacity
        style={[styles.buttonContainer, styles.buttonMute]}
        onPress={this.muteUnmuteAudio}
      >
        <MaterialIcon name={type} size={32} color="white" />
      </TouchableOpacity>
    );
  };

  _renderSwitchVideoSourceButton = () => {
    const { isFrontCamera } = this.state;
    const type = isFrontCamera ? "camera-rear" : "camera-front";

    return (
      <TouchableOpacity
        style={[styles.buttonContainer, styles.buttonSwitch]}
        onPress={this.switchCamera}
      >
        <MaterialIcon name={type} size={32} color="white" />
      </TouchableOpacity>
    );
  };

  render() {
    const { isActiveSelect, isActiveCall } = this.props;
    const isCallInProgress = isActiveCall || !isActiveSelect;
    const isAvailableToSwitch =
      isActiveCall && CallService.mediaDevices.length > 1;

    return (
      <SafeAreaView style={styles.container}>
        <View style={styles.toolBarItem}>
          {isActiveCall && this._renderMuteButton()}
        </View>
        <View style={styles.toolBarItem}>
          {this._renderCallStartStopButton(isCallInProgress)}
        </View>
        <View style={styles.toolBarItem}>
          {isAvailableToSwitch && this._renderSwitchVideoSourceButton()}
        </View>
      </SafeAreaView>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    position: "absolute",
    bottom: 20,
    left: 0,
    right: 0,
    height: 60,
    flex: 1,
    justifyContent: "center",
    flexDirection: "row",
    zIndex: 100,
  },
  toolBarItem: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonContainer: {
    height: 50,
    width: 50,
    borderRadius: 25,
    marginHorizontal: 25,
    justifyContent: "center",
    alignItems: "center",
  },
  buttonCall: {
    backgroundColor: "green",
  },
  buttonCallEnd: {
    backgroundColor: "red",
  },
  buttonMute: {
    backgroundColor: "blue",
  },
  buttonSwitch: {
    backgroundColor: "orange",
  },
});

```

**Comment by LiamInJapan** [comment]
VideoScreen/UsersSelect.js
```
import React from "react";
import { View, Text, StyleSheet, TouchableOpacity } from "react-native";
import MaterialIcon from "react-native-vector-icons/MaterialIcons";
import { shallowEqual, useSelector } from "react-redux";
import { CallService } from "../../../services";

export default ({
  isActiveSelect,
  opponentsIds,
  selectedUsersIds,
  selectUser,
  unselectUser,
}) => {
  const users = useSelector(
    (state) => state.group.allGroupMembers,
    shallowEqual
  );
  if (!isActiveSelect) {
    return null;
  }
  return (
    <View style={styles.container}>
      <Text style={styles.title}>Select users to start Videocall</Text>
      {opponentsIds.map((id) => {
        console.log(users);
        const user = CallService.getUserById(id, "name", users);
        const selected = selectedUsersIds.some((userId) => id === userId);
        const type = selected
          ? "radio-button-checked"
          : "radio-button-unchecked";
        const onPress = selected ? unselectUser : selectUser;

        return (
          <TouchableOpacity
            key={id}
            style={styles.userLabel("#34c3eb")}
            onPress={() => onPress(id)}
          >
            <Text style={styles.userName}>{user}</Text>
            <MaterialIcon name={type} size={20} color="white" />
          </TouchableOpacity>
        );
      })}
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    ...StyleSheet.absoluteFill,
    justifyContent: "center",
    alignItems: "center",
  },
  title: {
    fontSize: 20,
    color: "#1198d4",
    padding: 20,
  },
  userLabel: (backgroundColor) => ({
    backgroundColor,
    width: 150,
    height: 50,
    borderRadius: 25,
    paddingHorizontal: 15,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    margin: 5,
  }),
  userName: { color: "white", fontSize: 20 },
});

```

**Comment by LiamInJapan** [comment]
CallService.js
```
import { Platform, ToastAndroid } from "react-native";
import Toast from "react-native-simple-toast";
import ConnectyCube from "react-native-connectycube";
import InCallManager from "react-native-incall-manager";
import Sound from "react-native-sound";

export default class CallService {
  static MEDIA_OPTIONS = { audio: true, video: { facingMode: "user" } };

  _session = null;
  mediaDevices = [];

  outgoingCall = new Sound(require("../../../assets/sounds/dialing.mp3"));
  incomingCall = new Sound(require("../../../assets/sounds/calling.mp3"));
  endCall = new Sound(require("../../../assets/sounds/end_call.mp3"));

  showToast = (text) => {
    const commonToast = Platform.OS === "android" ? ToastAndroid : Toast;

    commonToast.showWithGravity(text, Toast.LONG, Toast.TOP);
  };

  getUserById = (userId, key, users) => {
    if (users === undefined) return;
    const user = users.find((user) => user.chatId == userId);
    if (typeof key === "string") {
      return user[key];
    }

    return user;
  };

  setMediaDevices() {
    return ConnectyCube.videochat.getMediaDevices().then((mediaDevices) => {
      this.mediaDevices = mediaDevices;
    });
  }

  acceptCall = (session) => {
    this.stopSounds();
    this._session = session;
    this.setMediaDevices();

    return this._session
      .getUserMedia(CallService.MEDIA_OPTIONS)
      .then((stream) => {
        this._session.accept({});
        return stream;
      });
  };

  startCall = (ids) => {
    const options = {};
    const type = ConnectyCube.videochat.CallType.VIDEO; // AUDIO is also possible

    this._session = ConnectyCube.videochat.createNewSession(ids, type, options);
    this.setMediaDevices();
    this.playSound("outgoing");

    return this._session
      .getUserMedia(CallService.MEDIA_OPTIONS)
      .then((stream) => {
        this._session.call({});
        return stream;
      });
  };

  stopCall = () => {
    this.stopSounds();

    if (this._session) {
      this.playSound("end");
      this._session.stop({});
      ConnectyCube.videochat.clearSession(this._session.ID);
      this._session = null;
      this.mediaDevices = [];
    }
  };

  rejectCall = (session, extension) => {
    this.stopSounds();
    session.reject(extension);
  };

  setAudioMuteState = (mute) => {
    if (mute) {
      this._session.mute("audio");
    } else {
      this._session.unmute("audio");
    }
  };

  switchCamera = (localStream) => {
    localStream.getVideoTracks().forEach((track) => track._switchCamera());
  };

  setSpeakerphoneOn = (flag) => InCallManager.setSpeakerphoneOn(flag);

  processOnUserNotAnswerListener(userId) {
    return new Promise((resolve, reject) => {
      if (!this._session) {
        reject();
      } else {
        const userName = this.getUserById(userId, "name");
        const message = `${userName} did not answer`;

        this.showToast(message);

        resolve();
      }
    });
  }

  processOnCallListener(session) {
    return new Promise((resolve, reject) => {
      if (session.initiatorID === session.currentUserID) {
        reject();
      }

      if (this._session) {
        this.rejectCall(session, { busy: true });
        reject();
      }

      this.playSound("incoming");

      resolve();
    });
  }

  processOnAcceptCallListener(session, userId, extension = {}) {
    return new Promise((resolve, reject) => {
      if (userId === session.currentUserID) {
        this._session = null;
        this.showToast("You have accepted the call on other side");

        reject();
      } else {
        const userName = this.getUserById(userId, "name");
        const message = `${userName} has accepted the call`;

        this.showToast(message);
        this.stopSounds();

        resolve();
      }
    });
  }

  processOnRejectCallListener(session, userId, extension = {}) {
    return new Promise((resolve, reject) => {
      if (userId === session.currentUserID) {
        this._session = null;
        this.showToast("You have rejected the call on other side");

        reject();
      } else {
        const userName = this.getUserById(userId, "name");
        const message = extension.busy
          ? `${userName} is busy`
          : `${userName} rejected the call request`;

        this.showToast(message);

        resolve();
      }
    });
  }

  processOnStopCallListener(userId, isInitiator) {
    return new Promise((resolve, reject) => {
      this.stopSounds();

      if (!this._session) {
        reject();
      } else {
        const userName = this.getUserById(userId, "name");
        const message = `${userName} has ${
          isInitiator ? "stopped" : "left"
        } the call`;

        this.showToast(message);

        resolve();
      }
    });
  }

  processOnRemoteStreamListener = () => {
    return new Promise((resolve, reject) => {
      if (!this._session) {
        reject();
      } else {
        resolve();
      }
    });
  };

  playSound = (type) => {
    switch (type) {
      case "outgoing":
        this.outgoingCall.setNumberOfLoops(-1);
        this.outgoingCall.play();
        break;
      case "incoming":
        this.incomingCall.setNumberOfLoops(-1);
        this.incomingCall.play();
        break;
      case "end":
        this.endCall.play();
        break;

      default:
        break;
    }
  };

  stopSounds = () => {
    if (this.incomingCall.isPlaying()) {
      this.incomingCall.pause();
    }
    if (this.outgoingCall.isPlaying()) {
      this.outgoingCall.pause();
    }
  };
}

```

**Comment by LiamInJapan** [comment]
Bootstrap.js

**Comment by DaveLomber** [comment]
@LiamInJapan please contact at support@connectycube.com
it might be easier to jump on a call and resolve it
